// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mobile-redesign/BoldTech.tsx": () => import("../components/mockups/mobile-redesign/BoldTech.tsx"),
  "./components/mockups/mobile-redesign/DarkMinimal.tsx": () => import("../components/mockups/mobile-redesign/DarkMinimal.tsx"),
  "./components/mockups/mobile-redesign/Glassmorphism.tsx": () => import("../components/mockups/mobile-redesign/Glassmorphism.tsx")
};
